select * from customers

--Q1.What is the total revenue generated by male vs. female customers ?
select gender,sum(cast(purchase_amount as int))as revenue
from customers
group by gender

--Q2.Which customers used a discount but stil spent more than the average purchase amount ?
select customer_id,purchase_amount
from customers
where discount_applied='Yes' and purchase_amount >=
                                (select avg(cast( purchase_amount as int) )from customers)

--Q3.Total Revenue Generated
SELECT 
    SUM(cast(purchase_amount as int)) AS Total_Revenue
FROM customers;

--Q4.Top 5 Most Purchased Products
SELECT 
    item_purchased,
    COUNT(*) AS Total_Orders
FROM customers
GROUP BY item_purchased
ORDER BY Total_Orders DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

--Q5.Top 5 Products with Highest Average Rating
SELECT 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS Average_Rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating as float)) DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

--Q6.Total Revenue by Product
SELECT 
    item_purchased,
    SUM(cast(purchase_amount as int)) AS Total_Revenue
FROM customers
GROUP BY item_purchased
ORDER BY Total_Revenue DESC;

--Q7.Top 5 Customers by Total Spending
SELECT 
    customer_id,
    SUM(cast(purchase_amount as int)) AS Total_Spent
FROM customers
GROUP BY customer_id
ORDER BY Total_Spent DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

--Q8. Customers Who Gave Low Ratings (< 3)
SELECT 
    customer_id,
    item_purchased,
    cast(review_rating as float) as review_rating
FROM customers
WHERE cast(review_rating as float) < 3
ORDER BY cast(review_rating as float) ASC;

--Q9.Revenue Contribution by Age Group
SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS Age_Group,
    SUM(cast(purchase_amount as int)) AS Total_Revenue
FROM customers
GROUP BY 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END
ORDER BY Total_Revenue DESC;

--Q10.Average Spending by Gender
SELECT 
    gender,
    ROUND(AVG(CAST(purchase_amount as int)), 2) AS Avg_Spending
FROM customers
GROUP BY gender;














